name: AiSEG2 Scene Controller
version: "1.0"
slug: aieseg2_scene

startup: services
boot: auto

arch:
  - amd64
  - aarch64

host_network: true

options:
  mqtt_user: "homeassistant"
  mqtt_password: ""

schema:
  mqtt_user: str
  mqtt_password: password